name: appifylab_task
version: 1.0.0+1
publish_to: 'none'
description: "Appifylab Task"
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_auth: ^4.19.6
  firebase_auth_platform_interface: ^7.2.7
  firebase_core: ^2.31.1
  firebase_database: ^10.5.6
  firebase_messaging: ^14.9.3
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logger: ^2.3.0
  nb_utils: ^7.0.2
  path: any
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path_ios: "assets/images/app_logo.png"
  image_path_android: "assets/images/app_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/


